server:
  port: 9002

spring:
  application:
    name: user
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: MUZI
    password: a123
mybatis:
  type-aliases-package: com.example.pojo
  configuration:
    map-underscore-to-camel-case: true


