server:
  port: 9001
spring:
  application:
    name: item
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#  datasource:
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
#    username: MUZI
#    password: a123




